apiVersion: v1
kind: Pod
metadata:
  name: bash-pod
spec:
  containers:
    - name: bash
      image: debian:bookworm-slim
      command: ["/bin/bash", "-c", "sleep infinity"]
      tty: true
      stdin: true
  restartPolicy: Never
