apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: aws-load-balancer-controller
    namespace: kube-system
    repo: https://aws.github.io/eks-charts
    releaseName: aws-load-balancer-controller
    version: 1.11.0
    includeCRDs: true
    valuesInline:
      clusterName: "sample"
      vpcId: "vpc-123456"
      serviceAccount:
        create: true
        name: aws-load-balancer-controller
      region: "ap-northeast-1"
    valuesFile: values.yaml

