---
apiVersion: v1
kind: Namespace
metadata:
  name: eks-sample-batch
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: eks-sample-batch
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              command:
                - /bin/sh
                - -c
                - |
                - date; echo Hello from the Kubernetes cluster > /dev/stdout;
          restartPolicy: OnFailure
