apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: test-karpenter
spec:
  ttlSecondsUntilExpired: 900
  ttlSecondsAfterEmpty: 30
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["t4g.medium"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["ap-northeast-1a", "ap-northeast-1c"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
  limits:
    resources:
      cpu: "1000"
      memory: 1000Gi
  provider:
    tags:
      karpenter.sh/discovery: test-karpentertest
    subnetSelector:
      karpenter.sh/discovery: test-karpenter
    securityGroupSelector:
      karpenter.sh/discovery: test-karpenter
    instanceProfile: KarpenterNodeInstanceProfile-test-karpenter

