apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: template-
  namespace: argo
spec:
  arguments:
    parameters:
      - name: shell
        value: echo 'workflow 01'
  workflowTemplateRef:
    name: template-01
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: template-
  namespace: argo
spec:
  workflowTemplateRef:
    name: template-01
  arguments:
    parameters:
      - name: shell
        value: "ls -la"
