apiVersion: v1
kind: Pod
metadata:
  name: aws-cli-debug
spec:
  serviceAccountName: example # ここにSAの名前を指定することでSAのAnnotationsに記載のIAMRoleを使うようになる
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: [ "/bin/sh", "-c", "sleep 3600" ]  # 長時間起動させる
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
  restartPolicy: Never

